"""fix forigen key

Revision ID: 0d4baae8a99b
Revises: dec330c42e4f
Create Date: 2022-11-13 12:36:53.341305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d4baae8a99b"
down_revision = "dec330c42e4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("accounts", sa.Column("status_id", sa.Integer(), nullable=False))
    op.add_column("accounts", sa.Column("type_id", sa.Integer(), nullable=True))
    op.add_column("accounts", sa.Column("currency_id", sa.Integer(), nullable=False))
    op.drop_constraint("accounts_user_id_fkey", "accounts", type_="foreignkey")
    op.create_foreign_key(None, "accounts", "account_types", ["type_id"], ["id"])
    op.create_foreign_key(None, "accounts", "currencies", ["currency_id"], ["id"])
    op.create_foreign_key(None, "accounts", "statuses", ["status_id"], ["id"])
    op.drop_column("accounts", "user_id")
    op.drop_constraint("currencies_account_id_fkey", "currencies", type_="foreignkey")
    op.drop_column("currencies", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currencies",
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "currencies_account_id_fkey", "currencies", "accounts", ["account_id"], ["id"]
    )
    op.add_column(
        "accounts",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.create_foreign_key(
        "accounts_user_id_fkey", "accounts", "users", ["user_id"], ["id"]
    )
    op.drop_column("accounts", "currency_id")
    op.drop_column("accounts", "type_id")
    op.drop_column("accounts", "status_id")
    op.drop_table("statuses")
    op.drop_table("account_types")
    # ### end Alembic commands ###
