"""fk fix

Revision ID: c8a15f2264bf
Revises: 789977fb08d3
Create Date: 2022-11-13 13:04:49.110956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a15f2264bf'
down_revision = '789977fb08d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
