"""add code to currency

Revision ID: c8f78c2330f9
Revises: 0d4baae8a99b
Create Date: 2022-11-13 12:51:15.802782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f78c2330f9'
down_revision = '0d4baae8a99b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'code')
    # ### end Alembic commands ###
