"""fix date type

Revision ID: eca09faea741
Revises: ca7fb2801ad4
Create Date: 2022-11-27 15:33:37.588770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca09faea741'
down_revision = 'ca7fb2801ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
