"""fix date type

Revision ID: ca7fb2801ad4
Revises: c63573136c28
Create Date: 2022-11-27 15:32:46.005148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7fb2801ad4'
down_revision = 'c63573136c28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
