"""fix date type by hand

Revision ID: f3d5f33a170d
Revises: eca09faea741
Create Date: 2022-11-27 15:44:17.586760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d5f33a170d'
down_revision = 'eca09faea741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('operations', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('operations', 'datetime')
    # ### end Alembic commands ###
